---

- name: install homebrew packages
  homebrew:
    upgrade_all: no
    name: "{{ item }}"
    state: present
  with_items:
    - coreutils
    - moreutils
    - findutils
    # - homebrew/dupes/grep
    - grc
    - the_silver_searcher
    - zsh
    - watch
    - htop
  tags:
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - google-chrome
    - sublime-text
    - slack
  tags:
    - homebrew