---

- name: install homebrew packages
  homebrew:
    upgrade_all: no
    name: "{{ item }}"
    state: present
  with_items:
    - coreutils
    - moreutils
    - findutils
    # - homebrew/dupes/grep
    - grc
    - the_silver_searcher
    - zsh
    - watch
    - htop
  tags:
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - google-chrome
    - sublime-text
    - slack
  tags:
    - homebrew

- name: "select dotfiles: ~/.dotfiles/<topic>/<file>.symlink"
  find:
    path: "{{ ansible_env.HOME}}/.dotfiles/"
    recurse: yes
    pattern: "*.symlink"
  register: files_to_symlink
  tags:
    - dotfiles

- name: "symlink: ~/.<file> -> ~/.dotfiles/<topic>/<file>.symlink"
  file:
    src: "{{ item.path }}"
    dest: "{{ ansible_env.HOME}}/.{{ item.path|basename|replace('.symlink', '') }}"
    state: link
  with_items: "{{files_to_symlink.files}}"
  tags:
    - dotfiles

- name: Determine if zsh is default/current shell
  shell: echo $SHELL
  register: current_shell
  tags:
    - zsh

- name: Enable zsh in /etc/shells
  shell: sudo /bin/sh -c 'grep -q "{{ zsh_path }}" /etc/shells || echo "{{ zsh_path }}" >> /etc/shells'
  when: current_shell.stdout != "{{zsh_path}}"
  tags:
    - zsh

- name: Set zsh as default shell
  shell: chsh -s {{ zsh_path }}
  when: current_shell.stdout != "{{zsh_path}}"
  tags:
    - zsh

- name: Clone/Update oh-my-zsh repo
  git: 
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ ansible_env.HOME}}/.oh-my-zsh"
  tags:
    - zsh
