---

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - java
    - eclipse-java
  tags:
    - homebrew

- name: install homebrew packages
  homebrew:
    upgrade_all: no
    package:
      - maven
      - gradle
    state: present
  tags:
    - homebrew
