---

- name: OSX Sys Config | System
  shell: "{{ item }}"
  with_items: 
   - "{{ osx_config.system }}"
  become: yes
  become_method: sudo


###############################################################################
# General UI/UX                                                               #
###############################################################################

  
# - name: Set highlight color to grey
#   osx_defaults: domain=NSGlobalDomain key=AppleHighlightColor value="0.847059 0.847059 0.862745"

- name: Set dark mode
  osx_defaults: domain=NSGlobalDomain key=AppleInterfaceStyle value=Dark

- name: Set sidebar icon size to small
  osx_defaults: domain=NSGlobalDomain key=NSTableViewDefaultSizeMode type=int value=1

# - name: Always show scrollbars
#   osx_defaults: domain=NSGlobalDomain key=AppleShowScrollBars value="Always"

- name: Expand save panel by default
  osx_defaults: domain=NSGlobalDomain key=NSNavPanelExpandedStateForSaveMode type=bool value=true

- name: Expand save panel by default 2
  osx_defaults: domain=NSGlobalDomain key=NSNavPanelExpandedStateForSaveMode2 type=bool value=true

- name: Expand print panel by default
  osx_defaults: domain=NSGlobalDomain key=PMPrintingExpandedStateForPrint type=bool value=true

- name: Expand print panel by default 2
  osx_defaults: domain=NSGlobalDomain key=PMPrintingExpandedStateForPrint2 type=bool value=true

- name: Save to disk (not to iCloud) by default
  osx_defaults: domain=NSGlobalDomain key=NSDocumentSaveNewDocumentsToCloud type=bool value=false

- name: Automatically quit printer app once the print jobs complete
  osx_defaults: domain=com.apple.print.PrintingPrefs key="Quit When Finished" type=bool value=true

- name: Disable the “Are you sure you want to open this application?” dialog
  osx_defaults: domain=com.apple.LaunchServices key=LSQuarantine type=bool value=false

# - name: Reveal IP address, hostname, etc. when clicking the clock in the login window
#   osx_defaults: domain=/Library/Preferences/com.apple.loginwindow key=AdminHostInfo value=HostName
#   become: yes
#   become_method: sudo

- name: Disable smart quotes as they’re annoying when typing code
  osx_defaults: domain=NSGlobalDomain key=NSAutomaticQuoteSubstitutionEnabled type=bool value=false

- name: Disable smart dashes as they’re annoying when typing code
  osx_defaults: domain=NSGlobalDomain key=NSAutomaticDashSubstitutionEnabled type=bool value=false

###############################################################################
# Trackpad, mouse, keyboard, Bluetooth accessories, and input                 #
###############################################################################

- name: Enable “natural” scrolling
  osx_defaults: domain=NSGlobalDomain key=com.apple.swipescrolldirection type=bool value=true

- name: Enable full keyboard access for all controls
  osx_defaults: domain=NSGlobalDomain key=AppleKeyboardUIMode type=int value=3

- name: Disable press-and-hold for keys in favor of key repeat
  osx_defaults: domain=NSGlobalDomain key=ApplePressAndHoldEnabled type=bool value=false

- name: Set a fast keyboard repeat rate
  osx_defaults: domain=NSGlobalDomain key=KeyRepeat type=int value=2


- name: Restart things so that changes take effect
  shell: "{{ item }}"
  with_items: 
   - killall Dock
   - killall Finder
   - killall SystemUIServer
  become: yes
  become_method: sudo
