---

osx_config:
  
  system:
    # Disable the sound effects on boot
    # - nvram SystemAudioVolume=" "

    # Reveal IP address, hostname, OS version, etc. when clicking the clock
    # in the login window
    #- sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

