---

osx_config:
  
  system:
    # Disable the sound effects on boot
    # - nvram SystemAudioVolume=" "

    # Disable transparency in the menu bar and elsewhere on Yosemite
    # - defaults write com.apple.universalaccess reduceTransparency -bool true

    # show menus
    # - defaults write com.apple.systemuiserver menuExtras -array "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" "/System/Library/CoreServices/Menu Extras/AirPort.menu" "/System/Library/CoreServices/Menu Extras/Battery.menu" "/System/Library/CoreServices/Menu Extras/Clock.menu"

    # Set highlight color to grey
    # - defaults write NSGlobalDomain AppleHighlightColor -string "0.847059 0.847059 0.862745"

    # Set dark mode
    # - defaults write NSGlobalDomain AppleInterfaceStyle Dark

    # Set sidebar icon size to small
    #- defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

    # Always show scrollbars
    #- defaults write NSGlobalDomain AppleShowScrollBars -string "Always"

    # Expand save panel by default
    #- defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
    #- defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

    # Expand print panel by default
    #- defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
    #- defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true

    # Save to disk (not to iCloud) by default
    #- defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false

    # Automatically quit printer app once the print jobs complete
    #- defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true

    # Disable the “Are you sure you want to open this application?” dialog
    #- defaults write com.apple.LaunchServices LSQuarantine -bool false

    # Reveal IP address, hostname, OS version, etc. when clicking the clock
    # in the login window
    #- sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

    # Disable smart quotes as they’re annoying when typing code
    #- defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

    # Disable smart dashes as they’re annoying when typing code
    #- defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
