---
# Dev: stuff need for most dev eenvironments


- name: install homebrew packages
  homebrew:
    upgrade_all: no
    package:
      - colordiff
      - fzf
      - git
      - git-extras
      - gti
      - tig
      - tmux
      - vim
    state: present
  tags:
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - thonny
    - visual-studio-code
  tags:
    - homebrew

- name: Clone/Update tmux plugin manager repo
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME}}/.tmux/plugins/tpm"
  tags:
    - homebrew
