---
# Dev: stuff need for most dev eenvironments


- name: install homebrew packages
  homebrew:
    upgrade_all: no
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - tig
    - git-extras
    - gti
    - rlwrap
    - ssh-copy-id
    - colordiff
    - tmux
    - reattach-to-user-namespace
    - shellcheck
  tags:
    - homebrew

- name: install homebrew vim
  homebrew:
    upgrade_all: no
    name: vim
    state: present
    install_options: with-override-system-vi
  tags:
    - homebrew


- name: Clone/Update tmux plugin manager repo
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME}}/.tmux/plugins/tpm"
  tags:
    - homebrew
