---

- name: install homebrew packages
  homebrew:
    upgrade_all: no
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - tig
    - git-extras
    - gti
    - rlwrap
    - ssh-copy-id
    - colordiff
    - https://raw.githubusercontent.com/Homebrew/homebrew/cff239addef86cc2bdeac6d97bd57992540f2ace/Library/Formula/python.rb
  tags:
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - postgres
    - dockertoolbox
    - datagrip
  tags:
    - homebrew