---
# Dev: stuff need for most dev eenvironments


- name: install homebrew packages
  homebrew:
    upgrade_all: no
    package:
      - colordiff
      - git
      - git-extras
      - gti
      - pipx
      - reattach-to-user-namespace
      - rlwrap
      - shellcheck
      - ssh-copy-id
      - teensy_loader_cli
      - tig
      - tmux
      - vim
    state: present
  tags:
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - teensy
  tags:
    - homebrew

- name: Clone/Update tmux plugin manager repo
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_env.HOME}}/.tmux/plugins/tpm"
  tags:
    - homebrew
