---

- name: install homebrew packages
  homebrew:
    upgrade_all: no
    name: "{{ item }}"
    state: present
  with_items:
    - pyenv
    - pyenv-virtualenv
  tags:
    - homebrew

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - pycharm
  tags:
    - homebrew
