---

- name: install system level python packages
  pip:
    name: "{{ item }}"
    extra_args: --user
    state: latest
  with_items:
    - stevedore
    - virtualenv
    - virtualenvwrapper
    - ipython
    - ptpython
  environment:
    PIP_REQUIRE_VIRTUALENV: ""
  tags:
    - python

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - pycharm
  tags:
    - homebrew
