---

- name: install system level python packages
  pip:
    name: "{{ item }}"
    extra_args: --user
    state: latest
  with_items:
    - stevedore
    - virtualenv
    - virtualenvwrapper
    - ipython
    - ptpython
    - pycharm
  environment:
    PIP_REQUIRE_VIRTUALENV: ""
  tags:
    - python
