# Install command-line tools using Homebrew
# Usage: `brew bundle Brewfile`

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
#upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install some other useful utilities like `sponge`
install moreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, `g`-prefixed
install findutils
# Install GNU `sed`, overwriting the built-in `sed`
#install gnu-sed --default-names

# Install more recent versions of some OS X tools
install vim --override-system-vi
install homebrew/dupes/grep
install homebrew/dupes/screen

# Install other useful binaries
install ant
install git
install gradle
install grc
install gti
install imagemagick --with-webp
install maven
install python
install rlwrap
install scala
install ssh-copy-id
install the_silver_searcher
install tig
install tmux
install watch
install zsh
#install zsh-syntax-highlighting


# Remove outdated versions from the cellar
cleanup