---

- name: install homebrew packages
  homebrew:
    upgrade_all: no
    name: "{{ item }}"
    state: present
  with_items:
    - kubernetes-cli
    - kubernetes-helm
  tags:
    - homebrew


- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items:
    - datagrip
    - docker
    - postgres
  tags:
    - homebrew
