---
# Base: stuff needed for provisioning to run.

- name: check for xcode
  command: xcode-select --version
  register: xcode
  ignore_errors: true
  tags:
    - homebrew

- name: xcode failure
  fail:
    msg: "XCode is not correctly installed, halting Homebrew installation. Retry after manually installing Xcode & Xcode Command Line Tools."
  when: xcode.rc != 0
  tags:
    - homebrew

- name: check for homebrew
  stat: path=/opt/homebrew/bin/brew
  register: brew
  tags:
    - homebrew

- name: install homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" 
  when: not brew.stat.exists
  tags:
    - homebrew

- name: update homebrew
  homebrew:
    update_homebrew: yes
    upgrade_all: no
  tags:
    - homebrew

- name: install homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items:
    - homebrew/cask-fonts
  tags:
    - homebrew
