---
# Usage:  ansible-playbook -i provisioning/inventory provisioning/provision.yml -e "ROLE=<role>"

- name: Applying role [{{ROLE}}]
  hosts: all

  pre_tasks:
    # - name: install roles from ansible-galaxy
    #   local_action: command ansible-galaxy install -r requirements.yml


  roles:
  - { role: '{{ROLE}}' }