---

- name: Provision a new machine
  hosts: all

  pre_tasks:
    # - name: install roles from ansible-galaxy
    #   local_action: command ansible-galaxy install -r requirements.yml


  roles:
    # eventually we'll want to be able to choose home/work
    # probably based on hostname
    - common
    - dev
    - dev-python
    - dev-data
    - dev-java
